name: Sync Fork

on:
  schedule:
    - cron: '54 3 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: google
          base: master
          head: master
